name: API Tests

on:
  workflow_dispatch:

concurrency:
  group: api-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    runs-on: ubuntu-latest
    env:
      ALLURE_RESULTS: allure-results-api
      ALLURE_REPORT: allure-report

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Clean previous Allure
        run: |
          rm -rf "$ALLURE_RESULTS" "$ALLURE_REPORT" || true

      - name: Run API tests
        run: npm run test:api

      - name: Generate Allure HTML
        run: npx allure generate --clean "./$ALLURE_RESULTS" -o "./$ALLURE_REPORT"

      - name: Upload Allure results (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-allure-results
          path: ${{ env.ALLURE_RESULTS }}
          retention-days: 7

      - name: Upload Allure report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-allure-report
          path: ${{ env.ALLURE_REPORT }}
          retention-days: 7
